package com.example.thread

class Consts {
    companion object {
        val cases = arrayOf(
            "Revolution Case",
            "Spectrum Case",
            "Revolver Case",
            "Operation Vanguard Weapon Case",
            "Operation Phoenix Weapon Case",
            "Shadow Case",
            "Horizon Case",
            "Gamma Case",
            "Glove Case",
            "Prisma Case",
            "Falchion Case",
            "Fracture Case",
            "Recoil Case",
            "Gamma 2 Case",
            "Chroma Case",
            "CS20 Case",
            "Chroma 2 Case",
            "Danger Zone Case",
            "Snakebite Case",
            "Clutch Case",
            "Prisma 2 Case",
            "Spectrum 2 Case",
            "Operation Hydra Case",
            "Shattered Web Case",
            "Operation Bravo Case",
            "Chroma 3 Case",
            "eSports 2013 Case",
            "Operation Breakout Weapon Case",
            "Dreams Nightmares Case",
            "Operation Wildfire Case",
            "Operation Riptide Case",
            "Winter Offensive Weapon Case",
            "CS:GO Weapon Case",
            "Operation Broken Fang Case",
            "eSports 2013 Winter Case",
            "eSports 2014 Summer Case",
            "CS:GO Weapon Case 2",
            "CS:GO Weapon Case 3",
            "Huntsman Weapon Case"
        )
        val casesImg = arrayOf(
            R.drawable.revolution_case,
            R.drawable.spectrum_case,
            R.drawable.revolver_case,
            R.drawable.operation_vanguard_weapon_case,
            R.drawable.operation_phoenix_weapon_case,
            R.drawable.shadow_case,
            R.drawable.horizon_case,
            R.drawable.gamma_case,
            R.drawable.glove_case,
            R.drawable.prisma_case,
            R.drawable.falchion_case,
            R.drawable.fracture_case,
            R.drawable.recoil_case,
            R.drawable.gamma_2_case,
            R.drawable.chroma_case,
            R.drawable.cs20_case,
            R.drawable.chroma_2_case,
            R.drawable.danger_zone_case,
            R.drawable.snakebite_case,
            R.drawable.clutch_case,
            R.drawable.prisma_2_case,
            R.drawable.spectrum_2_case,
            R.drawable.operation_hydra_case,
            R.drawable.shattered_web_case,
            R.drawable.operation_bravo_case,
            R.drawable.chroma_3_case,
            R.drawable.esports_2013_case,
            R.drawable.operation_breakout_weapon_case,
            R.drawable.dreams_nightmares_case,
            R.drawable.operation_wildfire_case,
            R.drawable.operation_riptide_case,
            R.drawable.winter_offensive_weapon_case,
            R.drawable.csgo_weapon_case,
            R.drawable.operation_broken_fang_case,
            R.drawable.esports_2013_winter_case,
            R.drawable.esports_2014_summer_case,
            R.drawable.csgo_weapon_case_2,
            R.drawable.csgo_weapon_case_3,
            R.drawable.huntsman_weapon_case
        )

        const val BASE_URL = "https://steamcommunity.com/"


    }
}